export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_OBTENER_USUARIO = 'AUTH_OBTENER_USUARIO';

export const BARRIOS_LOADING = 'BARRIOS_LOADING';
export const BARRIOS_ERROR = 'BARRIOS_ERROR';
export const BARRIOS_TRAER_TODOS = 'BARRIOS_TRAER_TODOS';
export const BARRIOS_TRAER_UNO = 'BARRIOS_TRAER_UNO';
export const BARRIOS_AGREGAR = 'BARRIOS_AGREGAR';
export const BARRIOS_MODIFICAR = 'BARRIOS_MODIFICAR';
export const BARRIOS_ELIMINAR = 'BARRIOS_ELIMINAR';

export const LOCALIDADES_LOADING = 'LOCALIDADES_LOADING';
export const LOCALIDADES_ERROR = 'LOCALIDADES_ERROR';
export const LOCALIDADES_TRAER_TODAS = 'LOCALIDADES_TRAER_TODAS';
export const LOCALIDADES_TRAER_UNO = 'LOCALIDADES_TRAER_UNO';
export const LOCALIDADES_AGREGAR = 'LOCALIDADES_AGREGAR';
export const LOCALIDADES_MODIFICAR = 'LOCALIDADES_MODIFICAR';
export const LOCALIDADES_ELIMINAR = 'LOCALIDADES_ELIMINAR';
export const LOCALIDADES_FILTRAR = 'LOCALIDADES_FILTRAR';

export const PARTIDOS_LOADING = 'PARTIDOS_LOADING';
export const PARTIDOS_ERROR = 'PARTIDOS_ERROR';
export const PARTIDOS_TRAER_TODOS = 'PARTIDOS_TRAER_TODOS';
export const PARTIDOS_TRAER_UNO = 'PARTIDOS_TRAER_UNO';
export const PARTIDOS_AGREGAR = 'PARTIDOS_AGREGAR';
export const PARTIDOS_MODIFICAR = 'PARTIDOS_MODIFICAR';
export const PARTIDOS_ELIMINAR = 'PARTIDOS_ELIMINAR';